name: Continuous Integration

on: pull_request:
  branches:
    'main'

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Using Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23.
      -name: run install, build and test
        run:|
          npm install
          npm run build
          npm run test
